/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haroldev' at '10/04/17 11:51' with Gradle 2.14.1
 *
 * @author haroldev, @date 10/04/17 11:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
